import './functions/stravaAuth.js'
import './functions/stravaCallback.js'
import './functions/stravaStatus.js'
import './functions/segments.js'
import './functions/segmentStar.js'
import './functions/userSettings.js'
import './functions/athleteEfforts.js'
import './functions/stravaWebhook.js'
